desktop: Use registered categories
This causes the following error when building with flatpak-builder:

    error: value "Utility;Productivity;GTK;" for key "Categories" in group
    "Desktop Entry" contains an unregistered value "Productivity";
    values extending the format should start with "X-"

"Productivity" is not a known category as the Desktop Menu Specification
by Freedesktop.org: https://specifications.freedesktop.org/menu-spec/1.0/category-registry.html

So use the registered category "Clock" instead and use "Productivity"
as a keyword which is a free form